version: '3'

services:

  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    volumes:
      - portainer-data:/data
    ports:
      - "9000:9000/tcp"
    networks:
      - portainer

  portainer-agent:
    image: portainer/agent:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer
    deploy:
      placement:
        constraints: [node.platform.os == linux]

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    command: "-c"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    networks:
      - portainer
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

volumes:
  portainer-data:

networks:
  portainer:
