version: "2.1"
volumes:
  unificontrollerconfig:
services:
  controller:
    image: ghcr.io/linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - unificontrollerconfig:/config
    ports:
      - 3478:3478/udp # Unifi STUN port
      - 10001:10001/udp # Required for AP discovery
      - 8080:8080 # Required for device communication
      - 8443:8443 # Unifi web admin port
      - 1900:1900/udp # Required for Make controller discoverable on L2 network option
      - 6789:6789 # For mobile throughput test
    network_mode: "host"
    restart: always
